import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { League_Spartan } from "next/font/google";
import "./globals.css";

const league_spartan = League_Spartan({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${league_spartan.className} bg-mobileImage bg-neutral-white bg-no-repeat  container lg:container mx-auto text-basic md:bg-image md:bg-no-repeat`}
      >
        {children}
      </body>
    </html>
  );
}
